# Generated by Django 6.1 on 2026-08-12 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit / product code. Auto-generated if left blank.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current selling price. Changing this does not affect past invoices.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What the business pays to acquire/produce this item. Used for profit reports.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PCS", "Piece"),
                            ("KG", "Kilogram"),
                            ("LTR", "Litre"),
                            ("BOX", "Box"),
                            ("PACK", "Pack"),
                            ("MTR", "Meter"),
                            ("OTHER", "Other"),
                        ],
                        default="PCS",
                        max_length=10,
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current quantity on hand. Adjusted automatically via StockMovement records.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Trigger a 'low stock' warning when stock_quantity falls to/below this level.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Disable for services or items where stock isn't tracked (e.g. labor, delivery fees).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive products are hidden from sale but preserved for historical invoices.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Stock Purchase / Restock"),
                            ("SALE", "Sale (Invoice)"),
                            ("RETURN", "Customer Return"),
                            ("ADJUSTMENT_IN", "Manual Adjustment (Increase)"),
                            ("ADJUSTMENT_OUT", "Manual Adjustment (Decrease)"),
                            ("DAMAGED", "Damaged / Written Off"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "resulting_stock",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of stock_quantity immediately after this movement.",
                        max_digits=12,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Invoice number, purchase order number.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "-created_at"], name="products_st_product_3ae061_idx"
            ),
        ),
    ]
