# Generated by Django 6.1 on 2026-08-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Stock Keeping Unit / product code. Auto-generated if left blank.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
